# Change these first
owner: frost-linux # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Frost Linux Website
    url: https://frost-linux.github.io
  - name: Frost Linux GitHub Mirror
    url: https://frost-linux.github.io/comet

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://github.com/frost-linux/frost-linux.github.io/blob/main/variant-1-no-boundary.png?raw=true
  name: Frost Linux Status
  introTitle: "Frost Linux Website Health Monitor."
  introMessage: This website gives an update on the health and uptime of Frost Linux mirrors and related websites.
  navbar:
    - title: Uptime Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Website
      href: https://frost-linux.github.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
