# Change these first
owner: frost-linux # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: Frost Linux Website
    url: https://frost-linux.github.io
  - name: Frost Linux GitHub Mirror
    url: https://frost-linux.github.io/comet

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Frost Linux Status
  introTitle: "This is Frost Linux's mirror monitor and status page, powered entirely by GitHub."
  introMessage: This website gives an update on the health and uptime of Frost Linux mirrors and related websites.
  navbar:
    - title: Uptime Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
